version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=recordsdb
      - POSTGRES_USER=recordssuser
      - POSTGRES_PASSWORD=icdrecords
    ports:
    - "5434:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=recordsdb
      - DB_USER=recordssuser
      - DB_PASS=icdrecords
    volumes:
      - .:/records
    ports:
      - "8000:8000"

    depends_on:
      - db
volumes:
  postgres_data: