version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=icddb
      - POSTGRES_USER=icduser
      - POSTGRES_PASSWORD=icd@123
    ports:
    - "5434:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart:
    volumes:
      - .:/records
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: