version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
   
    environment:
      - POSTGRES_DB=recordsdb
      - POSTGRES_USER=recordssuser
      - POSTGRES_PASSWORD=records@123
    

  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - db
      
volumes:
  postgres_data: