# Generated by Django 4.0.4 on 2022-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(choices=[('icd_9', 'ICD_9 2008'), ('icd_10', 'ICD_10 2015'), ('icd_11', 'ICD_11 2022')], default='icd_10', max_length=20)),
                ('category_code', models.CharField(max_length=6, null=True)),
                ('code_id', models.CharField(max_length=5, null=True)),
                ('addition_code', models.CharField(max_length=10)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(default='')),
                ('category_title', models.CharField(max_length=20)),
            ],
        ),
    ]
