# Generated by Django 4.0.4 on 2022-04-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(choices=[('icd_9', 'ICD_9 2008'), ('icd_10', 'ICD_10 2015'), ('icd_11', 'ICD_11 2022')], default='icd_10', max_length=10)),
                ('category_code', models.CharField(max_length=6, null=True)),
                ('category_title', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=5, null=True)),
                ('summary', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.category')),
            ],
        ),
    ]
