# Generated by Django 4.0.4 on 2022-04-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=6, null=True)),
                ('category_title', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisCodes',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=6, null=True)),
                ('code_id', models.CharField(max_length=5, null=True)),
                ('summary', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=40)),
                ('category_title', models.CharField(max_length=20, null=True)),
                ('icd_code', models.CharField(default='ICD_10', max_length=8, null=True)),
            ],
        ),
    ]
