# Generated by Django 4.0.4 on 2022-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_diagnosiscodes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosiscodes',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='diagnosiscodes',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
