# Generated by Django 4.0.4 on 2022-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_diagnosiscodes_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosiscodes',
            name='category_title',
            field=models.CharField(max_length=200),
        ),
    ]
