# Generated by Django 4.0.4 on 2022-04-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_diagnosiscodes_full_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='diagnosiscodes',
            old_name='full_code',
            new_name='addition_code',
        ),
    ]
